### ISSUE TITLE
用真实gt_cls替代预测分类分支值   有几个问题想请教

### ISSUE THREAD

**Issue by czy341181** [hyz-xmaster/VarifocalNet#13]
Table2中的对比实验。
是把分类分支的max score用1去替换吗？
如果这样的话，
1.nms的排序这些框不都是1了吗，怎么去做nms呢？
2.另外，做完nms后，去评估AP值的时候，score都是1，据我的了解，AP是对score敏感的，那这样还怎么计算AP啊？

**Comment by hyz-xmaster** [comment]
In my understanding, you are referring to Table 1 rather than Table 2, right? 

gt_cls means replacing the  classification score with the value of 1.0 at the ground-truth label position. For example, [0.1, 0.3, 0.6] -> [0.1, 0.3, 1.0], assuming the gt label is 3 (0.6 -> 1.0).  This indicates the perfect classification for the generated bounding box. 

Please be aware that this experiment aims to find out the performance barrier of current dense detectors. It is not part of the evaluation of our proposed algorithm.

**Comment by czy341181** [comment]
但是这样在评估的时候，score不都是1.0了吗。AP的计算不是需要对score进行排序吗，这样性能不会下降吗

**Comment by czy341181** [comment]
我知道这只是想验证检测的上界，并不是方法部分。我只是想知道这部分验证实验的一些细节。还望赐教

**Comment by hyz-xmaster** [comment]
Not all generated bounding boxes will have a score of 1.0, but only those boxes which are generated from a few of points inside the gt boxes, i.e foreground points defined by ATSS, will be given a new score of 1.0. Others will be unchanged.

**Comment by czy341181** [comment]
Ideally, it is necessary to make the score of the estimated more accurate box as high as possible, right?  If they are all set to 1.0, the boxes of these positive samples are considered to be very accurate, Can this indicate the upper boundary?

**Comment by hyz-xmaster** [comment]
This upper boundary is achieved by the perfect classification of bounding boxes (here perfect classification means assigning a correct label to a bounding box without considering its spatial accuracy), and as you see it is limited, although it is higher than the original performance (43.1 vs 38.5) . On the other hand, as shown in Table 1, if you can predict perfect IACSs (gt_cls_iou) as the detection score, the upper boundary is quite high.

**Comment by czy341181** [comment]
OK, thanks for your patient reply! I have no problem
